export const badwords_hindi = [
  { w: "aand" },
  { w: "aandu" },
  { w: "balatkar" },
  { w: "beti chod" },
  { w: "bhadva" },
  { w: "bhadve" },
  { w: "bhandve" },
  { w: "bhootni ke" },
  { w: "bhosad" },
  { w: "bhosadi ke" },
  { w: "boobe" },
  { w: "chakke" },
  { w: "chinaal" },
  { w: "chinki" },
  { w: "chod" },
  { w: "chodu" },
  { w: "chodu bhagat" },
  { w: "chooche" },
  { w: "choochi" },
  { w: "choot" },
  { w: "choot ke baal" },
  { w: "chootia" },
  { w: "chootiya" },
  { w: "chuche" },
  { w: "chuchi" },
  { w: "chudai khanaa" },
  { w: "chudan chudai" },
  { w: "chut" },
  { w: "chut ke baal" },
  { w: "chut ke dhakkan" },
  { w: "chut maarli" },
  { w: "chutad" },
  { w: "chutadd" },
  { w: "chutan" },
  { w: "chutia" },
  { w: "chutiya" },
  { w: "gaand" },
  { w: "gaandfat" },
  { w: "gaandmasti" },
  { w: "gaandufad" },
  { w: "gandu" },
  { w: "gashti" },
  { w: "gasti" },
  { w: "ghassa" },
  { w: "ghasti" },
  { w: "harami" },
  { w: "haramzade" },
  { w: "hawas" },
  { w: "hawas ke pujari" },
  { w: "hijda" },
  { w: "hijra" },
  { w: "jhant" },
  { w: "jhant chaatu" },
  { w: "jhant ke baal" },
  { w: "jhantu" },
  { w: "kamine" },
  { w: "kaminey" },
  { w: "kanjar" },
  { w: "kutta" },
  { w: "kutta kamina" },
  { w: "kutte ki aulad" },
  { w: "kutte ki jat" },
  { w: "kuttiya" },
  { w: "loda" },
  { w: "lodu" },
  { w: "lund" },
  { w: "lund choos" },
  { w: "lund khajoor" },
  { w: "lundtopi" },
  { w: "lundure" },
  { w: "maa ki chut" },
  { w: "maal" },
  { w: "madar chod" },
  { w: "mooh mein le" },
  { w: "mutth" },
  { w: "najayaz" },
  { w: "najayaz aulaad" },
  { w: "najayaz paidaish" },
  { w: "paki" },
  { w: "pataka" },
  { w: "patakha" },
  { w: "raand" },
  { w: "randi" },
  { w: "saala" },
  { w: "saala kutta" },
  { w: "saali kutti" },
  { w: "saali randi" },
  { w: "suar" },
  { w: "suar ki aulad" },
  { w: "tatte" },
  { w: "tatti" },
  { w: "teri maa ka bhosada" },
  { w: "teri maa ka boba chusu" },
  { w: "teri maa ki chut" },
  { w: "tharak" },
  { w: "tharki" }
];
